services:
    tms_merge_token.tokenizer:
        class: Tms\Bundle\TmsMergeTokenBundle\Tokenizer
        arguments: [@tms_merge_token.processor_handler]

    tms_merge_token.processor_handler:
        class: Tms\Bundle\TmsMergeTokenBundle\Processor\ProcessorHandler

    # Processors
    tms_merge_token.processor.arithmetic:
        class: Tms\Bundle\TmsMergeTokenBundle\Processor\ArithmeticProcessor
        arguments: []
        tags: 
            - { name: tms_merge_token.processor, alias: "Arithmetic" }

    tms_merge_token.processor.directory:
        class: Tms\Bundle\TmsMergeTokenBundle\Processor\DirectoryProcessor
        arguments: []
        tags: 
            - { name: tms_merge_token.processor, alias: "Directory" }

    tms_merge_token.processor.document:
        class: Tms\Bundle\TmsMergeTokenBundle\Processor\DocumentProcessor
        arguments: []
        tags: 
            - { name: tms_merge_token.processor, alias: "Document" }

    tms_merge_token.processor.form_field:
        class: Tms\Bundle\TmsMergeTokenBundle\Processor\FormFieldProcessor
        arguments: []
        tags: 
            - { name: tms_merge_token.processor, alias: "FormField" }

    tms_merge_token.processor.object:
        class: Tms\Bundle\TmsMergeTokenBundle\Processor\ObjectProcessor
        arguments: []
        tags: 
            - { name: tms_merge_token.processor, alias: "Object" }

    tms_merge_token.processor.route:
        class: Tms\Bundle\TmsMergeTokenBundle\Processor\RouteProcessor
        arguments: []
        tags: 
            - { name: tms_merge_token.processor, alias: "Route" }

