services:

    tms_merge_token.event.subscriber.serializer:
        class: Tms\Bundle\MergeTokenBundle\Event\Subscriber\SerializerSubscriber
        arguments: [@twig]
        tags:
            - { name: jms_serializer.event_subscriber }
