services:
    tms_merge_token.tokenizer:
        class: Tms\Bundle\TmsMergeTokenBundle\Tokenizer
        arguments: [@tms_merge_token.processor_handler]

    tms_merge_token.processor_handler:
        class: Tms\Bundle\TmsMergeTokenBundle\Processor\ProcessorHandler

    # Processors
    tms_merge_token.processor.arithmetic:
        class: Tms\Bundle\TmsMergeTokenBundle\Processor\ArithmeticProcessor
        tags: 
            - { name: tms_merge_token.processor, alias: "Arithmetic" }

    tms_merge_token.processor.directory:
        class: Tms\Bundle\TmsMergeTokenBundle\Processor\DirectoryProcessor
        arguments: [@doctrine.orm.entity_manager]
        tags: 
            - { name: tms_merge_token.processor, alias: "Directory" }

    tms_merge_token.processor.doctrine_orm:
        class: Tms\Bundle\TmsMergeTokenBundle\Processor\DoctrineORMProcessor
        arguments: [@doctrine.orm.entity_manager]
        tags: 
            - { name: tms_merge_token.processor, alias: "DoctrineORM" }

    tms_merge_token.processor.route:
        class: Tms\Bundle\TmsMergeTokenBundle\Processor\RouteProcessor
        arguments: [@router]
        tags: 
            - { name: tms_merge_token.processor, alias: "Route" }

